# Sales Records Analysis
### Author: Marenza Santarin
### Exercise 2.E Using functions for analyzing data
This notebook analyzes a small sales dataset using Python functions.
Each function takes the full dataset as its first argument.

In [55]:
sales_data = [
('Laptop', 'East', 1200.00),
('Phone', 'West', 850.00),
('Tablet', 'East', 400.00),
('Monitor', 'South', 650.00),
('Keyboard', 'West', 75.00),
('Laptop', 'South', 1150.00),
('Phone', 'East', 900.00),
('Tablet', 'West', 425.00),
('Monitor', 'East', 680.00),
('Keyboard', 'South', 80.00),
('Laptop', 'West', 1300.00),
('Phone', 'West', 820.00),
]

## Lab 1. Total sales by region

In [56]:
# Find the total sales amount for a specific region
def region_total(data, region):
    return sum(amt for _, r, amt in data if r == region)
# The underscore holds the product name which is not needed for this calculation
# r is for the region and amt is for the amount of the sale
# The if r == region condition checks whether the region matches region asked for in the function

In [57]:
# Printing the total sales amount for each region with formatted output
# Updated the formatting output from the lab work to include commas for thousands and two decimal places for cents
print(f"${region_total(sales_data, 'East'):,.2f}")
print(f"${region_total(sales_data, 'West'):,.2f}")
print(f"${region_total(sales_data, 'South'):,.2f}")

$3,180.00
$3,470.00
$1,880.00


## Lab 2. Count of sales by region

In [58]:
# Counting how many sales were made in a specific region
def region_count(data, region):
    return sum(1 for _, r, _ in data if r == region)
# This function counts the number of sales in a specific region by summing 1 for each matching record
# The underscore in the sum function is used to ignore the product name and amount since they are not needed for counting
# The if r == region condition checks whether the region matches region asked for in the function

In [59]:
# Printing the count of sales for each region
print(region_count(sales_data, 'East'))
print(region_count(sales_data, 'West'))
print(region_count(sales_data, 'South'))
print(region_count(sales_data, 'North'))

4
5
3
0


## Lab 3. Average sale amount by region

In [60]:
# Calculate the average sales amount for a specific region
# The average is calculated by dividing the total sales amount for the region by the count of sales in that region
def region_average(data, region):
    count = region_count(data, region)

    # If there are no sales in the region, return 0 to avoid division by zero
    if count == 0:
        return 0
    
    total = region_total(data, region)
    return total / count

In [61]:
# Printing the average sales amount for each region with formatted output
print(f"East Average   :  ${region_average(sales_data, 'East'):,.2f}")
print(f"West Average   :  ${region_average(sales_data, 'West'):,.2f}")
print(f"South Average  :  ${region_average(sales_data, 'South'):,.2f}")
print(f"North Average  :  ${region_average(sales_data, 'North'):,.2f}")

East Average   :  $795.00
West Average   :  $694.00
South Average  :  $626.67
North Average  :  $0.00


## Lab 4. Filter by sale amount

In [62]:
# Find all sales records where the amount exceeds a certain threshold
def sales_above(data, threshold):
    return [(product, region, amt) for product, region, amt in data if amt > threshold]
# This will keep the records where the amount of the sale is greater than the threshold specified 
# when calling the function and put it into a new list

# Example: Find all sales above $500
sales_above(sales_data, 500)

[('Laptop', 'East', 1200.0),
 ('Phone', 'West', 850.0),
 ('Monitor', 'South', 650.0),
 ('Laptop', 'South', 1150.0),
 ('Phone', 'East', 900.0),
 ('Monitor', 'East', 680.0),
 ('Laptop', 'West', 1300.0),
 ('Phone', 'West', 820.0)]

In [63]:
# Find all sales records where the amount is less than a certain threshold
def sales_below(data, threshold):
    return [(product, region, amt) for product, region, amt in data if amt < threshold]
# This will keep the records where the amount of the sale is less than the threshold specified 
# when calling the function and put it into a new list

# Example: Find all sales below $500
sales_below(sales_data, 500)

[('Tablet', 'East', 400.0),
 ('Keyboard', 'West', 75.0),
 ('Tablet', 'West', 425.0),
 ('Keyboard', 'South', 80.0)]

## Lab 5. Top and bottom sale

In [69]:
# Finding the sales record with the highest amount
def top_sale(data):
    return max(data, key=lambda s: s[2])
# The max function is used to find the highest sale, and the key parameter is set to a 
# lambda function that extracts the amount (s[2]) from each sale record for comparison
# Each sales record gets stored in the temporary variable s

# Finding the sales record with the lowest amount
def bottom_sale(data):
    return min(data, key=lambda s: s[2])
# The min function is used to find the lowest sale, and the key parameter is set to a 
# lambda function that extracts the amount (s[2]) from each sale record for comparison
# Each sales record gets stored in the temporary variable s

In [73]:
# Printing the highest and lowest sales records
print(top_sale(sales_data))
print(bottom_sale(sales_data))

('Laptop', 'West', 1300.0)
('Keyboard', 'West', 75.0)


The highest sale was Laptop in the West region for $1,300.00.

The lowest sale was Keyboard in the West region for $75.00.

## Lab 6. Apply a discout

In [81]:
# Applying a discount to all sales records
# map() means apply the function to every item in the list and the lambda function is used
# to create an anonymous function that takes a sales record s and returns a new tuple with 
# the same product and region but with the amount reduced by the discount percentage
# In (1 - discount_pct), 1 represents the full price and discount_pct is the percentage to be discounted
def apply_discount(data, discount_pct):
    return list(map(
        lambda s: (s[0], s[1], s[2] * (1 - discount_pct)),
        data
    ))

#The function returns a brand-new discounted list
discounted_sales = apply_discount(sales_data, 0.15)

In [83]:
# Printing the original and discounted sales records for comparison
# Only showing the first 3 records
print("Before Discount:")
for record in sales_data[:3]:
    print(record)

print("\nAfter Discount:")
for record in discounted_sales[:3]:
    print(record)

Before Discount:
('Laptop', 'East', 1200.0)
('Phone', 'West', 850.0)
('Tablet', 'East', 400.0)

After Discount:
('Laptop', 'East', 1020.0)
('Phone', 'West', 722.5)
('Tablet', 'East', 340.0)


## Lab 7. Unique regions

In [87]:
# Finding the unique regions from the sales records
def unique_regions(data):
    return sorted(set(region for _, region, _ in data))
# This loops through each sales record, extracts the region, and creates a set of unique regions
# The sorted function is used to return the unique regions in a sorted order

In [88]:
# Printing the unique regions from the sales records
print(unique_regions(sales_data))

['East', 'South', 'West']


This function could be useful for finding all available regions in a dataset. In a larger analysis program, it could help create reports by region, dashboards, or loops that summarize sales for each unique region without manually typing the region names.

## Lab 8. Region summary

In [110]:
# Creating a summary report for a specific region that includes total sales, count of sales, average sale amount, and the top sale
# The new region_data variable will hold rows for the selected region,, it is set to go to index 1 of each record since the region is at index 1 in the sales records
def region_summary(data, region):
    region_data = [row for row in data if row[1] == region]

    total = region_total(region_data, region)
    count = region_count(region_data, region)
    average = region_average(region_data, region)
    top_item, _, top_amount = top_sale(region_data)
    # This will unpack multiple values from the top_sale function, but we only need the product name and amount for the summary, so the region is ignored with an underscore

    # Printing the summary report for the specified region with formatted output
    print(f"============ {region} Region ============")
    print(f"Records      :  {count}")
    print(f"Total Sales  :  ${total:,.2f}")
    print(f"Average Sale :  ${average:,.2f}")
    print(f"Top Sale     :  {top_item} - ${top_amount:,.2f}")

region_summary(sales_data, 'East')

============ East Region ============
Records      :  4
Total Sales  :  $3,180.00
Average Sale :  $795.00
Top Sale     :  Laptop - $1,200.00


## Lab 9. Full summary

In [112]:
# This will call the unique_regions from lab 7 and will return a collection of region names,
# then the for loop will iterate through each region and call the region_summary function from lab 8
# to  print the summary report for each region in the sales data
for region in unique_regions(sales_data):
    region_summary(sales_data, region)
    print()

============ East Region ============
Records      :  4
Total Sales  :  $3,180.00
Average Sale :  $795.00
Top Sale     :  Laptop - $1,200.00

============ South Region ============
Records      :  3
Total Sales  :  $1,880.00
Average Sale :  $626.67
Top Sale     :  Laptop - $1,150.00

============ West Region ============
Records      :  5
Total Sales  :  $3,470.00
Average Sale :  $694.00
Top Sale     :  Laptop - $1,300.00

