# Data Analytics - Exercise 7.1: NumPy Essentials
## Marenza Santarin | 5/18/2026

This notebook uses NumPy to analyze the weekly revenue for five regional offices. It calculates statistics, applies bonus, filter above-average regions, and reshapes the dtaa into 2D arrays.

In [40]:
import numpy as np

# Creating the 1D array revenue to store the five weekly revenue values
revenue = np.array([52400.0, 38750.0, 61200.0, 47900.0, 55650.0])

print(f"Array : {revenue}")         # Shows the actual revenue values
print(f"dtype : {revenue.dtype}")   # Shows the data type | I think for whole numbers it will be 32 and for float it will be 64 
print(f"shape : {revenue.shape}")   # Shows the structure of the array or how much values are in it

Array : [52400. 38750. 61200. 47900. 55650.]
dtype : float64
shape : (5,)


In [41]:
# Using Numpy's built in functions for the calculation
print("----- Revenue Statistics -----")
print(f"Total   : ${np.sum(revenue):,.2f}")
print(f"Mean    : ${np.mean(revenue):,.2f}")
print(f"Median  : ${np.median(revenue):,.2f}")
print(f"Std Dev : ${np.std(revenue):,.2f}")
print(f"Minimum : ${np.min(revenue):,.2f}")
print(f"Maximum : ${np.max(revenue):,.2f}")

----- Revenue Statistics -----
Total   : $255,900.00
Mean    : $51,180.00
Median  : $52,400.00
Std Dev : $7,578.03
Minimum : $38,750.00
Maximum : $61,200.00


In [42]:
# Calculation for the bonus | Element-wise Arithmetic
# revenue * 1.05 means every number gets multiplied by 1.05
# The 1 keeps the original amount, and the .05 adds the extra 5%
revenue_bonus = revenue * 1.05
bonus_amount = revenue_bonus - revenue

print("Original Revenue   :", revenue)
print("Revenue + 5% Bonus :", revenue_bonus)
print("Bonus Amount       :", bonus_amount)


Original Revenue   : [52400. 38750. 61200. 47900. 55650.]
Revenue + 5% Bonus : [55020.  40687.5 64260.  50295.  58432.5]
Bonus Amount       : [2620.  1937.5 3060.  2395.  2782.5]


In [43]:
# This creates a true of false check for each region
# If the region's revenue is above the average, it will become true
# Then revenue[above_avg] only grabs the values where the answer was true
above_avg = revenue > np.mean(revenue)

print("Mask True/False       :", above_avg)
print("Above average         :", revenue[above_avg])
print(f"Regions above average : {np.sum(above_avg)}")

Mask True/False       : [ True False  True False  True]
Above average         : [52400. 61200. 55650.]
Regions above average : 3


In [44]:
# reshape(5, 1) changes the revenue array into 5 rows and 1 column
# np.vstack() stacks the arrays so there's 1 row for the original revenue and another row fror the bonus revenue
# axis=1 works across each row so it gives row totals
# axis=0 works down each column so it gives the average for each region
col_vec = revenue.reshape(5,1)
print("Column vector (5,1):\n", col_vec)

q_data = np.vstack([revenue, revenue * 1.05])
print("\n2D array:\n", q_data)

print("\nWeekly totals  :", np.sum(q_data, axis=1))
print("Region average :", np.mean(q_data, axis=0))

Column vector (5,1):
 [[52400.]
 [38750.]
 [61200.]
 [47900.]
 [55650.]]

2D array:
 [[52400.  38750.  61200.  47900.  55650. ]
 [55020.  40687.5 64260.  50295.  58432.5]]

Weekly totals  : [255900. 268695.]
Region average : [53710.   39718.75 62730.   49097.5  57041.25]


## Summary

The five regions generated a total of $255,900.00 in original weekly revenue. Three out of five regions performed above the average revenue of $51,180.00. After applying a 5% bonus, the total revenue increased to $268,695.00.